

all:
	g++ -o openMPRangeSearchRunner -O2 -fopenmp -I thirdParty/ -std=gnu++11	rangeSearch.cpp miscFunctions.cpp AtomNameToNumHashTable.cpp cpuBruteForceSearch.cpp printToFileHandler.cpp dataStructures.cpp cpuKdTreeSearch.cpp SearchStructureConstruction.cpp  ESBTL_ProteinHandler.cpp 




