

all:
	mpiCC -std=c++11 -o openMPIRangeSearch rangeSearch.cpp miscFunctions.cpp cpuKdTreeSearch.cpp AtomNameToNumHashTable.cpp cpuBruteForceSearch.cpp dataStructures.cpp rangeSearchHandler.cpp SearchStructureConstruction.cpp  ESBTL_ProteinHandler.cpp -I thirdParty/
